/**
 * Copyright Explore Consulting, LLC
 *
 * Utility library with functions that can be used for both client and server side SuiteScript
 */
// declare Explore 'namespace' if it's not already defined
if (typeof EC == "undefined" || !EC) {
    var EC = {};
}

/**
 * Represents US states. First one is blank I presume to allow easy binding to a UI dropdown?
 * @type {{id,name,abbrev}}
 */
var stateInfo = [ { name: "", id: "", abbrev: ""},
    {name: "Alabama", id: 0, abbrev: "AL"},
    {name: "Alaska", id: 1, abbrev: "AK"},
    {name: "Arizona", id: 2, abbrev: "AZ"},
    {name: "Arkansas", id: 3, abbrev: "AR"},
    {name: "Armed Forces Americas", id: 53, abbrev: "AA"},
    {name: "Armed Forces Europe", id: 52, abbrev: "AE"},
    {name: "Armed Forces Pacific", id: 54, abbrev: "AP"},
    {name: "California", id: 4, abbrev: "CA"},
    {name: "Colorado", id: 5, abbrev: "CO"},
    {name: "Connecticut", id: 6, abbrev: "CT"},
    {name: "Delaware", id: 7, abbrev: "DE"},
    {name: "District of Columbia", id: 8, abbrev: "DC"},
    {name: "Florida", id: 9, abbrev: "FL"},
    {name: "Georgia", id: 10, abbrev: "GA"},
    {name: "Hawaii", id: 11, abbrev: "HI"},
    {name: "Idaho", id: 12, abbrev: "ID"},
    {name: "Illinois", id: 13, abbrev: "IL"},
    {name: "Indiana", id: 14, abbrev: "IN"},
    {name: "Iowa", id: 15, abbrev: "IA"},
    {name: "Kansas", id: 16, abbrev: "KS"},
    {name: "Kentucky", id: 17, abbrev: "KY"},
    {name: "Louisiana", id: 18, abbrev: "LA"},
    {name: "Maine", id: 19, abbrev: "ME"},
    {name: "Maryland", id: 20, abbrev: "MD"},
    {name: "Massachusetts", id: 21, abbrev: "MA"},
    {name: "Michigan", id: 22, abbrev: "MI"},
    {name: "Minnesota", id: 23, abbrev: "MN"},
    {name: "Mississippi", id: 24, abbrev: "MS"},
    {name: "Missouri", id: 25, abbrev: "MO"},
    {name: "Montana", id: 26, abbrev: "MT"},
    {name: "Nebraska", id: 27, abbrev: "NE"},
    {name: "Nevada", id: 28, abbrev: "NV"},
    {name: "New Hampshire", id: 29, abbrev: "NH"},
    {name: "New Jersey", id: 30, abbrev: "NJ"},
    {name: "New Mexico", id: 31, abbrev: "NM"},
    {name: "New York", id: 32, abbrev: "NY"},
    {name: "North Carolina", id: 33, abbrev: "NC"},
    {name: "North Dakota", id: 34, abbrev: "ND"},
    {name: "Ohio", id: 35, abbrev: "OH"},
    {name: "Oklahoma", id: 36, abbrev: "OK"},
    {name: "Oregon", id: 37, abbrev: "OR"},
    {name: "Pennsylvania", id: 38, abbrev: "PA"},
    {name: "Puerto Rico", id: 39, abbrev: "PR"},
    {name: "Rhode Island", id: 40, abbrev: "RI"},
    {name: "South Carolina", id: 41, abbrev: "SC"},
    {name: "South Dakota", id: 42, abbrev: "SD"},
    {name: "Tennessee", id: 43, abbrev: "TN"},
    {name: "Texas", id: 44, abbrev: "TX"},
    {name: "Utah", id: 45, abbrev: "UT"},
    {name: "Vermont", id: 46, abbrev: "VT"},
    {name: "Virginia", id: 47, abbrev: "VA"},
    {name: "Washington", id: 48, abbrev: "WA"},
    {name: "West Virginia", id: 49, abbrev: "WV"},
    {name: "Wisconsin", id: 50, abbrev: "WI"},
    {name: "Wyoming", id: 51, abbrev: "WY"}
];

EC.getState = _.partial(_.find,stateInfo);


/**
 * Represents NetSuite internal and external IDs for all transaction types
 * @type {{external,internal}}
 */
var TransactionTypeMap = [
    {external:"Build",internal:"assemblybuild"},
    {external:"Unbuild",internal:"assemblyunbuild"},
    {external:"VendBill",internal:"vendorbill"},
    {external:"VendCard",internal:"Bill CCard"},
    {external:"VendCred",internal:"vendorcredit"},
    {external:"VendPymt",internal:"vendorpayment"},
    {external:"BinWksht",internal:"binworksheet"},
    {external:"BinTrnfr",internal:"bintransfer"},
    {external:"CardRfnd",internal:"CCard Refund"},
    {external:"CashRfnd",internal:"cashrefund"},
    {external:"CashSale",internal:"cashsale"},
    {external:"Check",internal:"check"},
    {external:"Commissn",internal:"Commission"},
    {external:"CardChrg",internal:"Credit Card"},
    {external:"CustCred",internal:"creditmemo"},
    {external:"FxReval",internal:"currency"},
    {external:"CustDep",internal:"customerdeposit"},
    {external:"CustRfnd",internal:"customerrefund"},
    {external:"Deposit",internal:"Deposit"},
    {external:"DepAppl",internal:"depositapplication"},
    {external:"Estimate",internal:"estimate"},
    {external:"ExpRept",internal:"expensereport"},
    {external:"InvAdjst",internal:"Inventory Adjustment"},
    {external:"InvDistr",internal:"Inventory Distribution"},
    {external:"InvTrnfr",internal:"Inventory Transfer"},
    {external:"InvWksht",internal:"Inventory Worksheet"},
    {external:"CustInvc",internal:"invoice"},
    {external:"ItemShip",internal:"itemfulfillment"},
    {external:"ItemRcpt",internal:"itemreceipt"},
    {external:"Journal",internal:"journalentry"},
    {external:"LiaAdjst",internal:"Liability Adjustment"},
    {external:"Opprtnty",internal:"opportunity"},
    {external:"Paycheck",internal:"Paycheck"},
    {external:"CustPymt",internal:"Payment"},
    {external:"YtdAdjst",internal:"Payroll Adjustment"},
    {external:"LiabPymt",internal:"Payroll Liability Check"},
    {external:"PurchOrd",internal:"purchaseorder"},
    {external:"RtnAuth",internal:"returnauthorization"},
    {external:"SalesOrd",internal:"salesorder"},
    {external:"TaxPymt",internal:"Sales Tax Payment"},
    {external:"CustChrg",internal:"Statement Charge"},
    {external:"TaxLiab",internal:"Tax Liability Cheque"},
    {external:"Transfer",internal:"transferorder"},
    {external:"VendAuth",internal:"vendorreturnauthorization"},
    {external:"WorkOrd",internal:"workorder"}
];

EC.getTransactionType = _.partial(_.find,TransactionTypeMap);

/**
 * Represents common countries.
 * @type {{id,name,abbrev}}
 */
var countryMapping = [ {name:"", id: "", abbrev: ""},
    {name: "Andorra", id: 1, abbrev: "AD"},
    {name: "United Arab Emirates", id: 2, abbrev: "AE"},
    {name: "Afghanistan", id: 3, abbrev: "AF"},
    {name: "Antigua and Barbuda", id: 4, abbrev: "AG"},
    {name: "Anguilla", id: 5, abbrev: "AI"},
    {name: "Albania", id: 6, abbrev: "AL"},
    {name: "Armenia", id: 7, abbrev: "AM"},
    {name: "Netherlands Antilles (Deprecated)", id: 8, abbrev: "AN"},
    {name: "Angola", id: 9, abbrev: "AO"},
    {name: "Antarctica", id: 10, abbrev: "AQ"},
    {name: "Argentina", id: 11, abbrev: "AR"},
    {name: "American Samoa", id: 12, abbrev: "AS"},
    {name: "Austria", id: 13, abbrev: "AT"},
    {name: "Australia", id: 14, abbrev: "AU"},
    {name: "Aruba", id: 15, abbrev: "AW"},
    {name: "Azerbaijan", id: 16, abbrev: "AZ"},
    {name: "Bosnia and Herzegovina", id: 17, abbrev: "BA"},
    {name: "Barbados", id: 18, abbrev: "BB"},
    {name: "Bangladesh", id: 19, abbrev: "BD"},
    {name: "Belgium", id: 20, abbrev: "BE"},
    {name: "Burkina Faso", id: 21, abbrev: "BF"},
    {name: "Bulgaria", id: 22, abbrev: "BG"},
    {name: "Bahrain", id: 23, abbrev: "BH"},
    {name: "Burundi", id: 24, abbrev: "BI"},
    {name: "Benin", id: 25, abbrev: "BJ"},
    {name: "Saint Barthélemy", id: 26, abbrev: "BL"},
    {name: "Bermuda", id: 27, abbrev: "BM"},
    {name: "Brunei Darussalam", id: 28, abbrev: "BN"},
    {name: "Bolivia", id: 29, abbrev: "BO"},
    {name: "Brazil", id: 30, abbrev: "BR"},
    {name: "Bahamas", id: 31, abbrev: "BS"},
    {name: "Bhutan", id: 32, abbrev: "BT"},
    {name: "Bouvet Island", id: 33, abbrev: "BV"},
    {name: "Botswana", id: 34, abbrev: "BW"},
    {name: "Belarus", id: 35, abbrev: "BY"},
    {name: "Belize", id: 36, abbrev: "BZ"},
    {name: "Canada", id: 37, abbrev: "CA"},
    {name: "Cocos (Keeling) Islands", id: 38, abbrev: "CC"},
    {name: "Congo, Democratic Republic of", id: 39, abbrev: "CD"},
    {name: "Central African Republic", id: 40, abbrev: "CF"},
    {name: "Congo, Republic of", id: 41, abbrev: "CG"},
    {name: "Switzerland", id: 42, abbrev: "CH"},
    {name: "Cote d'Ivoire", id: 43, abbrev: "CI"},
    {name: "Cook Islands", id: 44, abbrev: "CK"},
    {name: "Chile", id: 45, abbrev: "CL"},
    {name: "Cameroon", id: 46, abbrev: "CM"},
    {name: "China", id: 47, abbrev: "CN"},
    {name: "Colombia", id: 48, abbrev: "CO"},
    {name: "Costa Rica", id: 49, abbrev: "CR"},
    {name: "Serbia", id: 50, abbrev: "RS"},
    {name: "Serbia and Montenegro (Deprecated)", id: 51, abbrev: "CS"},
    {name: "Cuba", id: 52, abbrev: "CU"},
    {name: "Cape Verde", id: 53, abbrev: "CV"},
    {name: "Christmas Island", id: 54, abbrev: "CX"},
    {name: "Cyprus", id: 55, abbrev: "CY"},
    {name: "Czech Republic", id: 56, abbrev: "CZ"},
    {name: "Germany", id: 57, abbrev: "DE"},
    {name: "Djibouti", id: 58, abbrev: "DJ"},
    {name: "Denmark", id: 59, abbrev: "DK"},
    {name: "Dominica", id: 60, abbrev: "DM"},
    {name: "Dominican Republic", id: 61, abbrev: "DO"},
    {name: "Algeria", id: 62, abbrev: "DZ"},
    {name: "Ecuador", id: 63, abbrev: "EC"},
    {name: "Estonia", id: 64, abbrev: "EE"},
    {name: "Egypt", id: 65, abbrev: "EG"},
    {name: "Western Sahara", id: 66, abbrev: "EH"},
    {name: "Eritrea", id: 67, abbrev: "ER"},
    {name: "Spain", id: 68, abbrev: "ES"},
    {name: "Ethiopia", id: 69, abbrev: "ET"},
    {name: "Finland", id: 70, abbrev: "FI"},
    {name: "Fiji", id: 71, abbrev: "FJ"},
    {name: "Falkland Islands", id: 72, abbrev: "FK"},
    {name: "Micronesia, Federal State of", id: 73, abbrev: "FM"},
    {name: "Faroe Islands", id: 74, abbrev: "FO"},
    {name: "France", id: 75, abbrev: "FR"},
    {name: "Gabon", id: 76, abbrev: "GA"},
    {name: "United Kingdom", id: 77, abbrev: "GB"},
    {name: "Grenada", id: 78, abbrev: "GD"},
    {name: "Georgia", id: 79, abbrev: "GE"},
    {name: "French Guiana", id: 80, abbrev: "GF"},
    {name: "Guernsey", id: 81, abbrev: "GG"},
    {name: "Ghana", id: 82, abbrev: "GH"},
    {name: "Gibraltar", id: 83, abbrev: "GI"},
    {name: "Greenland", id: 84, abbrev: "GL"},
    {name: "Gambia", id: 85, abbrev: "GM"},
    {name: "Guinea", id: 86, abbrev: "GN"},
    {name: "Guadeloupe", id: 87, abbrev: "GP"},
    {name: "Equatorial Guinea", id: 88, abbrev: "GQ"},
    {name: "Greece", id: 89, abbrev: "GR"},
    {name: "South Georgia", id: 90, abbrev: "GS"},
    {name: "Guatemala", id: 91, abbrev: "GT"},
    {name: "Guam", id: 92, abbrev: "GU"},
    {name: "Guinea-Bissau", id: 93, abbrev: "GW"},
    {name: "Guyana", id: 94, abbrev: "GY"},
    {name: "Hong Kong", id: 95, abbrev: "HK"},
    {name: "Heard and McDonald Islands", id: 96, abbrev: "HM"},
    {name: "Honduras", id: 97, abbrev: "HN"},
    {name: "Croatia/Hrvatska", id: 98, abbrev: "HR"},
    {name: "Haiti", id: 99, abbrev: "HT"},
    {name: "Hungary", id: 100, abbrev: "HU"},
    {name: "Indonesia", id: 101, abbrev: "ID"},
    {name: "Ireland", id: 102, abbrev: "IE"},
    {name: "Israel", id: 103, abbrev: "IL"},
    {name: "Isle of Man", id: 104, abbrev: "IM"},
    {name: "India", id: 105, abbrev: "IN"},
    {name: "British Indian Ocean Territory", id: 106, abbrev: "IO"},
    {name: "Iraq", id: 107, abbrev: "IQ"},
    {name: "Iran (Islamic Republic of)", id: 108, abbrev: "IR"},
    {name: "Iceland", id: 109, abbrev: "IS"},
    {name: "Italy", id: 110, abbrev: "IT"},
    {name: "Jersey", id: 111, abbrev: "JE"},
    {name: "Jamaica", id: 112, abbrev: "JM"},
    {name: "Jordan", id: 113, abbrev: "JO"},
    {name: "Japan", id: 114, abbrev: "JP"},
    {name: "Kenya", id: 115, abbrev: "KE"},
    {name: "Kyrgyzstan", id: 116, abbrev: "KG"},
    {name: "Cambodia", id: 117, abbrev: "KH"},
    {name: "Kiribati", id: 118, abbrev: "KI"},
    {name: "Comoros", id: 119, abbrev: "KM"},
    {name: "Saint Kitts and Nevis", id: 120, abbrev: "KN"},
    {name: "Korea, Democratic People's Republic", id: 121, abbrev: "KP"},
    {name: "Korea, Republic of", id: 122, abbrev: "KR"},
    {name: "Kuwait", id: 123, abbrev: "KW"},
    {name: "Cayman Islands", id: 124, abbrev: "KY"},
    {name: "Kazakhstan", id: 125, abbrev: "KZ"},
    {name: "Lao People's Democratic Republic", id: 126, abbrev: "LA"},
    {name: "Lebanon", id: 127, abbrev: "LB"},
    {name: "Saint Lucia", id: 128, abbrev: "LC"},
    {name: "Liechtenstein", id: 129, abbrev: "LI"},
    {name: "Sri Lanka", id: 130, abbrev: "LK"},
    {name: "Liberia", id: 131, abbrev: "LR"},
    {name: "Lesotho", id: 132, abbrev: "LS"},
    {name: "Lithuania", id: 133, abbrev: "LT"},
    {name: "Luxembourg", id: 134, abbrev: "LU"},
    {name: "Latvia", id: 135, abbrev: "LV"},
    {name: "Libya", id: 136, abbrev: "LY"},
    {name: "Morocco", id: 137, abbrev: "MA"},
    {name: "Monaco", id: 138, abbrev: "MC"},
    {name: "Moldova, Republic of", id: 139, abbrev: "MD"},
    {name: "Montenegro", id: 140, abbrev: "ME"},
    {name: "Saint Martin", id: 141, abbrev: "MF"},
    {name: "Madagascar", id: 142, abbrev: "MG"},
    {name: "Marshall Islands", id: 143, abbrev: "MH"},
    {name: "Macedonia", id: 144, abbrev: "MK"},
    {name: "Mali", id: 145, abbrev: "ML"},
    {name: "Myanmar (Burma)", id: 146, abbrev: "MM"},
    {name: "Mongolia", id: 147, abbrev: "MN"},
    {name: "Macau", id: 148, abbrev: "MO"},
    {name: "Northern Mariana Islands", id: 149, abbrev: "MP"},
    {name: "Martinique", id: 150, abbrev: "MQ"},
    {name: "Mauritania", id: 151, abbrev: "MR"},
    {name: "Montserrat", id: 152, abbrev: "MS"},
    {name: "Malta", id: 153, abbrev: "MT"},
    {name: "Mauritius", id: 154, abbrev: "MU"},
    {name: "Maldives", id: 155, abbrev: "MV"},
    {name: "Malawi", id: 156, abbrev: "MW"},
    {name: "Mexico", id: 157, abbrev: "MX"},
    {name: "Malaysia", id: 158, abbrev: "MY"},
    {name: "Mozambique", id: 159, abbrev: "MZ"},
    {name: "Namibia", id: 160, abbrev: "NA"},
    {name: "New Caledonia", id: 161, abbrev: "NC"},
    {name: "Niger", id: 162, abbrev: "NE"},
    {name: "Norfolk Island", id: 163, abbrev: "NF"},
    {name: "Nigeria", id: 164, abbrev: "NG"},
    {name: "Nicaragua", id: 165, abbrev: "NI"},
    {name: "Netherlands", id: 166, abbrev: "NL"},
    {name: "Norway", id: 167, abbrev: "NO"},
    {name: "Nepal", id: 168, abbrev: "NP"},
    {name: "Nauru", id: 169, abbrev: "NR"},
    {name: "Niue", id: 170, abbrev: "NU"},
    {name: "New Zealand", id: 171, abbrev: "NZ"},
    {name: "Oman", id: 172, abbrev: "OM"},
    {name: "Panama", id: 173, abbrev: "PA"},
    {name: "Peru", id: 174, abbrev: "PE"},
    {name: "French Polynesia", id: 175, abbrev: "PF"},
    {name: "Papua New Guinea", id: 176, abbrev: "PG"},
    {name: "Philippines", id: 177, abbrev: "PH"},
    {name: "Pakistan", id: 178, abbrev: "PK"},
    {name: "Poland", id: 179, abbrev: "PL"},
    {name: "St. Pierre and Miquelon", id: 180, abbrev: "PM"},
    {name: "Pitcairn Island", id: 181, abbrev: "PN"},
    {name: "Puerto Rico", id: 182, abbrev: "PR"},
    {name: "State of Palestine", id: 183, abbrev: "PS"},
    {name: "Portugal", id: 184, abbrev: "PT"},
    {name: "Palau", id: 185, abbrev: "PW"},
    {name: "Paraguay", id: 186, abbrev: "PY"},
    {name: "Qatar", id: 187, abbrev: "QA"},
    {name: "Reunion Island", id: 188, abbrev: "RE"},
    {name: "Romania", id: 189, abbrev: "RO"},
    {name: "Russian Federation", id: 190, abbrev: "RU"},
    {name: "Rwanda", id: 191, abbrev: "RW"},
    {name: "Saudi Arabia", id: 192, abbrev: "SA"},
    {name: "Solomon Islands", id: 193, abbrev: "SB"},
    {name: "Seychelles", id: 194, abbrev: "SC"},
    {name: "Sudan", id: 195, abbrev: "SD"},
    {name: "Sweden", id: 196, abbrev: "SE"},
    {name: "Singapore", id: 197, abbrev: "SG"},
    {name: "Saint Helena", id: 198, abbrev: "SH"},
    {name: "Slovenia", id: 199, abbrev: "SI"},
    {name: "Svalbard and Jan Mayen Islands", id: 200, abbrev: "SJ"},
    {name: "Slovak Republic", id: 201, abbrev: "SK"},
    {name: "Sierra Leone", id: 202, abbrev: "SL"},
    {name: "San Marino", id: 203, abbrev: "SM"},
    {name: "Senegal", id: 204, abbrev: "SN"},
    {name: "Somalia", id: 205, abbrev: "SO"},
    {name: "Suriname", id: 206, abbrev: "SR"},
    {name: "Sao Tome and Principe", id: 207, abbrev: "ST"},
    {name: "El Salvador", id: 208, abbrev: "SV"},
    {name: "Syrian Arab Republic", id: 209, abbrev: "SY"},
    {name: "Swaziland", id: 210, abbrev: "SZ"},
    {name: "Turks and Caicos Islands", id: 211, abbrev: "TC"},
    {name: "Chad", id: 212, abbrev: "TD"},
    {name: "French Southern Territories", id: 213, abbrev: "TF"},
    {name: "Togo", id: 214, abbrev: "TG"},
    {name: "Thailand", id: 215, abbrev: "TH"},
    {name: "Tajikistan", id: 216, abbrev: "TJ"},
    {name: "Tokelau", id: 217, abbrev: "TK"},
    {name: "Turkmenistan", id: 218, abbrev: "TM"},
    {name: "Tunisia", id: 219, abbrev: "TN"},
    {name: "Tonga", id: 220, abbrev: "TO"},
    {name: "East Timor", id: 221, abbrev: "TL"},
    {name: "Turkey", id: 222, abbrev: "TR"},
    {name: "Trinidad and Tobago", id: 223, abbrev: "TT"},
    {name: "Tuvalu", id: 224, abbrev: "TV"},
    {name: "Taiwan", id: 225, abbrev: "TW"},
    {name: "Tanzania", id: 226, abbrev: "TZ"},
    {name: "Ukraine", id: 227, abbrev: "UA"},
    {name: "Uganda", id: 228, abbrev: "UG"},
    {name: "US Minor Outlying Islands", id: 229, abbrev: "UM"},
    {name: "United States", id: 230, abbrev: "US"},
    {name: "Uruguay", id: 231, abbrev: "UY"},
    {name: "Uzbekistan", id: 232, abbrev: "UZ"},
    {name: "Holy See (City Vatican State)", id: 233, abbrev: "VA"},
    {name: "Saint Vincent and the Grenadines", id: 234, abbrev: "VC"},
    {name: "Venezuela", id: 235, abbrev: "VE"},
    {name: "Virgin Islands (British)", id: 236, abbrev: "VG"},
    {name: "Virgin Islands (USA)", id: 237, abbrev: "VI"},
    {name: "Vietnam", id: 238, abbrev: "VN"},
    {name: "Vanuatu", id: 239, abbrev: "VU"},
    {name: "Wallis and Futuna", id: 240, abbrev: "WF"},
    {name: "Samoa", id: 241, abbrev: "WS"},
    {name: "Yemen", id: 242, abbrev: "YE"},
    {name: "Mayotte", id: 243, abbrev: "YT"},
    {name: "South Africa", id: 244, abbrev: "ZA"},
    {name: "Zambia", id: 245, abbrev: "ZM"},
    {name: "Zimbabwe", id: 246, abbrev: "ZW"},
    {name: "Aland Islands", id: 247, abbrev: "AX"},
    {name: "Ceuta and Melilla", id: 248, abbrev: "EA"},
    {name: "Canary Islands", id: 249, abbrev: "IC"},
    {name: "Bonaire, Saint Eustatius and Saba", id: 250, abbrev: "BQ"},
    {name: "Curaçao", id: 251, abbrev: "CW"},
    {name: "Sint Maarten", id: 252, abbrev: "SX"},
    {name: "South Sudan", id: 253, abbrev: "SS"},
    {name: "Kosovo", id: 254, abbrev: "XK"}
];

/**
 *  Lookup country data by one of 3 keys: internal id, abbreviation or country name. Providing any one
 *  of the three will exact match then return an object with all 3.
 * @type {function({name:string,id:number,abbrev:string})} country name, country internal id, and country 2-letter abbreviation
 * @example
 * //get by full name
 * EC.getCountry({ name:"United States"});
 *  {name:'United States', id: 230, abbrev: "US"}
 *
 * // get by abbreviation
 * EC.getCountry({ abbrev: "US" } );
 *  {name:'United States', id: 230, abbrev: "US"}
 *
 * // get by id
 * EC.getCountry( { id: '230' } );
 *  {name:'United States', id: 230, abbrev: "US"}
 */
EC.getCountry = _.partial(_.find, countryMapping);


/**
 * Represents NetSuite internal and external IDs for all item types
 * @type {Object}
 */
EC.ItemTypes = {
    InvtPart: "inventoryitem",
    NonInvtPart: "noninventoryitem",
    Group: "itemgroup",
    Kit: "kititem",
    Assembly: "assemblyitem",
    Service: "serviceitem",
    Description: "descriptionitem",
    Discount: "discountitem",
    OthCharge: "otherchargeitem",
    GiftCert: "giftcertificateitem",
    Markup: "markupitem",
    Payment: "paymentitem",
    Subtotal: "subtotalitem"
};

EC.isClientScript = (nlapiGetContext().getExecutionContext() == 'userinterface') && (typeof nlapiGetNewRecord !== 'function');

/**
 * Extracts as much useful debugging info as possible from exception types NetSuite likes to throw
 * @param e the exception to interrogate
 * @returns {string} a string containing error details, including stack trace info if available.
 */
EC.getExceptionDetail = function (e) {
    var detail = e.toString() + " \n";
    if (e.stack) detail += e.stack;
    else if (_.isFunction(e.getStackTrace)) detail += e.getStackTrace().join();
    else detail += "[no stack trace]";
    return detail;
};

